language: go
go:
- 1.4.2
script:
- go test -v -race ./...
notifications:
  hipchat:
    rooms:
      secure: bIX2HgfWudDg2C3MBM04O+uYGVTFH+UnZf0TkMpRDMLPC3B9opRjOcoob/LBHCWFCht1SQ5FCPEG0ZCY1JtkTD1aHlpgR9gOmj928r02Sg3O8M0szx21nyyBI+l+bl4Fkg16yqwmp9HEYLPXU+XIV581BuZdZuhc5orH3XPQZ1k=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
